use wasm_bindgen::prelude::*;

/**
* Each new term in the Fibonacci sequence is generated by adding the previous
* two terms. By starting with 1 and 2, the first 10 terms will be:
*
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
* By considering the terms in the Fibonacci sequence whose values
* do not exceed four million, find the sum of the even-valued terms.
*/

#[wasm_bindgen]
pub fn solve_2(max: u32) -> u32 {
    (0..max).fold(0, |acc, val| {
        if val % 3 == 0 || val % 5 == 0 {
            acc + val
        } else {
            acc
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sum_of_even_valued_fibonacci_numbers_under_4_million() {
        assert_eq!(solve_2(4000000), 4613732);
    }
}
